name: Release
on:
  push:
    paths:
      - 'src/harmonia/package.json'
  workflow_dispatch: # Allows manual triggering
jobs:
  release:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'src/harmonia/package-lock.json'
      - name: Install dependencies
        working-directory: ./src/harmonia
        run: npm ci
      - name: Build Electron app
        working-directory: ./src/harmonia
        run: npm run make
        env:
          # Code signing certificates (optional)
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # Windows code signing
          WIN_CSC_LINK: ${{ secrets.WIN_CSC_LINK }}
          WIN_CSC_KEY_PASSWORD: ${{ secrets.WIN_CSC_KEY_PASSWORD }}
          # Apple notarization (macOS)
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: src/harmonia/out/make/
          if-no-files-found: error
  create-release:
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      discussions: write
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
      - name: Get version from package.json
        id: get_version
        run: |
          echo "VERSION=$(jq -r .version src/harmonia/package.json)" >> $GITHUB_OUTPUT
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          files: |
            artifacts/**/*.exe
            artifacts/**/*.zip
            artifacts/**/*.dmg
            artifacts/**/*.AppImage
            artifacts/**/*.deb
            artifacts/**/*.rpm
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
